### ISSUE TITLE
Code tab examples bleeding

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/design-system-website#257] opened 2018-06-05 18:40 UTC
Code examples are a lot wider than they should be, in some instances they are bleeding off the pages. I am in Chrome, at 100%. It appears to be doing this on **all** pages. This includes the code snippet below it too

<img width="1125" alt="screen shot 2018-06-05 at 1 35 54 pm" src="https://user-images.githubusercontent.com/29312997/40995805-d34bc9ea-68c5-11e8-9df0-429afdb7e903.png">

In other instances its just pixels away from the right edge of the page

<img width="1127" alt="screen shot 2018-06-05 at 1 37 30 pm" src="https://user-images.githubusercontent.com/29312997/40995845-f162d428-68c5-11e8-9dfa-f0b694a63344.png">

**Comment by tw15egan** [comment] 2018-06-05 18:48
I'm not able to reproduce this, that's strange

**Comment by tay-aitken** [comment] 2018-06-05 19:14
Huh, maybe its my laptop?

**Comment by marijohannessen** [comment] 2018-06-05 19:32
I'm not seeing it either. What version of Chrome are you on @tay-aitken ?

**Comment by marijohannessen** [comment] 2018-06-06 16:52
Closing this as it was resolved when @tay-aitken updated her Chrome version

**Closed by marijohannessen** 2018-06-06 16:52 UTC
Labels: bug
